// players' data

export const players = [
  {
    id: 1,
    name: "Victor Osimhen",
    team: "Napoli FC",
    nationality: "Nigerian",
    jerseyNumber: "9",
    age: 26,
    imageURL: "https://cdn.futbin.com/content/fifa24/img/players/232293.png",
  },
  {
    id: 2,
    name: "Leo Messi",
    team: "Inter Miami",
    nationality: "Argentinian",
    jerseyNumber: "33",
    age: 36,
    imageURL: "https://cdn.futbin.com/content/fifa22/img/players/158023.png",
  },
  {
    id: 3,
    name: "Gaucho",
    team: "Fluminense",
    nationality: "Brazilian",
    jerseyNumber: "10",
    age: 40,
    imageURL: "https://cdn.futbin.com/content/fifa22/img/players/238706.png",
  },
  {
    id: 4,
    name: "Santi Carzola",
    team: "Real Oviedo",
    nationality: "Spanish",
    jerseyNumber: "8",
    age: 38,
    imageURL: "https://cdn.futbin.com/content/fifa20/img/players/146562.png",
  },
  {
    id: 5,
    name: "Dimitar Bebartov",
    team: "Manchester United",
    nationality: "Bulgarian",
    jerseyNumber: "32",
    age: 42,
    imageURL: "https://cdn.sofifa.net/players/030/110/16_360.png",
  },
  {
    id: 6,
    name: "Gigi Buffon",
    team: "Parma",
    nationality: "Italian",
    jerseyNumber: "1",
    age: 44,
    imageURL: "https://cdn.futbin.com/content/fifa23/img/players/1179.png",
  },
];
